{
    'name': 'Pmcpl Sale Discount on Total Amount',
    'version': '16.0.1.0.0',
    'category': 'Sales Management',
    'summary': "Discount on Total in Sale and Invoice With Discount Limit and Approval",
    'author': 'PMCPL',
    'company': 'Prime Minds Consulting Pvt Ltd',
    'website': 'http://www.primeminds.com',
    'description': """Sale Discount for Total Amount""",
    'depends': ['sale',
                'account', 'delivery'
                ],
    'data': [
        'views/res_config_view.xml',
        'views/sale_view.xml',
        'views/account_invoice_view.xml',
        'views/invoice_report.xml',
        'views/sale_order_report.xml',
    ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'application': True,
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
}